### ISSUE TITLE
Have k3s based unit tests

### ISSUE THREAD

**Issue by freeella** [freeella/kubectl-cpbase64#7]
It would be nice to  have test that copying real files from and to test PODs

Maybe `action-k3s-helm` is worth a try.

https://github.com/jupyterhub/action-k3s-helm/tree/main
https://github.com/jupyterhub/action-k3s-helm/blob/main/.github/workflows/test_k3s.yml

```yaml
name: Example workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  k8s-test:
    runs-on: ubuntu-22.04
    steps:
      # GitHub Action reference: https://github.com/jupyterhub/action-k3s-helm
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          # See available:
          # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
          # - k3s versions at https://github.com/k3s-io/k3s/tags
          # - helm versions at https://github.com/helm/helm/tags
          k3s-channel: latest
          # k3s-version: v1.29.0+k3s1
          # helm-version: v3.13.0

      - name: Verify function of k8s, kubectl, and helm
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get pods --all-namespaces

```
